class Airport < ApplicationRecord
  validates :icao, presence: true, uniqueness: true

  DEFAULT_ICAOS = "KECP,KINT,KLEE,KCTY,KGSP,KVLD,KPRN,KBKV,KPNS,KCLT,KGCY,KHDL,KVDI,KCTJ,KACJ,KMLJ,K3J7,KATL,KBHM,KCKF,KTCL,KASN,KTOC,KHXD,KJZP,KTOI,KEZM,KSSI,K17J,KCKV,KGNV,KDHN,KAND,KAGS,KCSV,KGVL,KMGM,KDTS,KTPA,KMCN,KMCO,KGZH,KCSG,KOPN,KTHA,KAZE,K79J,KGRD,KOCF,KABY,KMGR,KAVL,KGAD,KEUF,KFZG,KOGB,KLGC,KBIJ,KEDN,KOKZ,KAMG,KRMG,KDAB,KTLH,K2J3,KAYS,KLCQ,K6A1,KAAF,KBNA,KTYS,KCRG,KPDK,KMRC,KSRQ,KTMA,KAUO,KCAE,KTRI,KDBN,KHSV,KDNN,KTVI,KHOE,KSAV,K54J,KFHB,KAHN,KMAI,KTBR,KFPY,KWDR,KSEM,KDZJ,KCHA,KCXU,KVPC,KBGE,KLHW,K24J"
end